import type { Metadata } from "next";
import { Shadows_Into_Light_Two } from "next/font/google";

const Shadows = Shadows_Into_Light_Two({
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Dashboard - Sangeet",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main>{children}</main>;
}
